# Generated by Django 4.2.2 on 2024-02-29 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_alter_lesson_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='group',
            name='products',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='src.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='products',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='src.product'),
            preserve_default=False,
        ),
    ]
